@startuml
' Initial state
[*] --> Index

' state to allow naming and coloring
state "index.html (Forsiden)" as Index #Application
state "login.html" as Login #Aquamarine
state "createuser.html" as Opret #Aquamarine
state "customers.html" as Customers #Coral
state "orders.html" as Orders #Gold
state "orderdetails.html" as OrderDetails #Gold
state "checkout.html" as Checkout #Lightpink
state "receipt.html" as Receipt #Lightpink


' States
Index --> Login : "Login / Opret"
Index --> Orders : "Ordrer"
Orders --> Orders : "Slet ordre (Admin)"
Index --> Customers : "Kunder"
note left of Customers : Admin kan tilgå
Customers --> Index : "Tilbage til forsiden"

Index --> Checkout : "Se Indkøbskurv"

Login --> Opret : "Opret bruger"
Opret --> Index : "Tilbage til forsiden"

Orders --> OrderDetails : "Se ordredetaljer"
Orders --> Index : "Tilbage til forsiden"
OrderDetails --> Orders : "Tilbage til ordre"

Checkout --> Receipt : "Køb"
Checkout --> Checkout : "Fjern vare / Ryd kurv"

Receipt --> Index : "Tilbage til forsiden"


@enduml
