@startuml
' Layout direction
top to bottom direction

' Define classes
class "index.html (Forsiden)" as Index #33AAFF
class "login.html" as Login #FF7733
class "createuser.html" as Register #FF7733
class "customers.html" as Customers #FF7733
class "orders.html" as Orders #AACC77
class "orderdetails.html" as OrderDetails #AACC77
class "checkout.html" as Cart #FF7733
class "receipt.html" as Receipt #FF7733

' Navigation
Index --> Login : "Login / Opret"
Index --> Orders : "Ordrer"
Index --> Customers : "Kunder (Admin)"

Index --> Cart : "Se Indkøbskurv"
note right of Index : Tilbage til forsiden tilgængelig på alle sider
Login --> Register : "Opret bruger"

Orders --> OrderDetails : "Se ordredetaljer"
Orders --> Orders : "Slet ordre (Admin)"
OrderDetails --> Orders : "Tilbage til ordre"

Cart --> Receipt : "Køb"
Cart --> Cart : "Fjern vare"

@enduml
